FixError: The current Visual Studio version does not support targeting .NET 10.0.  Either target .NET 9.0 or lower, or use Visual Studio version 18.0 or higher